#!/usr/bin/env python3
"""
Smoke test for the bundled skill toolchain.

This repo has no application code to test, so what matters is whether the
skills in .agents/skills can actually run. Each check below drives a real
bundled script or the library a skill's SKILL.md tells Claude to reach for,
rather than asserting a package merely imports.

    python3 scripts/check-skills.py          # run everything
    python3 scripts/check-skills.py xlsx pdf # run named checks only

Exit code is 0 only when every check that ran passed.
"""

import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SKILLS = REPO / ".agents" / "skills"

GREEN, RED, DIM, OFF = "\033[32m", "\033[31m", "\033[2m", "\033[0m"
if not sys.stdout.isatty():
    GREEN = RED = DIM = OFF = ""

CHECKS = {}


def check(name):
    def wrap(fn):
        CHECKS[name] = fn
        return fn

    return wrap


def run(cmd, **kw):
    """Run a command, raising with its output attached when it fails."""
    kw.setdefault("capture_output", True)
    kw.setdefault("text", True)
    kw.setdefault("timeout", 180)
    proc = subprocess.run(cmd, **kw)
    if proc.returncode != 0:
        tail = (proc.stderr or proc.stdout or "").strip().splitlines()[-6:]
        raise AssertionError(
            f"{' '.join(str(c) for c in cmd[:3])}... exited {proc.returncode}\n"
            + "\n".join("        " + line for line in tail)
        )
    return proc


# --------------------------------------------------------------------------


@check("xlsx")
def check_xlsx(tmp):
    """Write a workbook with a formula, then recalculate it the way the skill does."""
    import json

    import openpyxl

    book = openpyxl.Workbook()
    sheet = book.active
    for row, value in enumerate([10, 20, 30], start=1):
        sheet.cell(row=row, column=1, value=value)
    sheet["A4"] = "=SUM(A1:A3)"
    path = tmp / "smoke.xlsx"
    book.save(path)

    recalc = SKILLS / "xlsx" / "scripts" / "recalc.py"
    out = run([sys.executable, str(recalc), str(path)]).stdout
    report = json.loads(out[out.index("{"):])
    assert report.get("status") == "success", f"recalc reported {report}"

    got = openpyxl.load_workbook(path, data_only=True).active["A4"].value
    assert got == 60, f"SUM(A1:A3) came back as {got!r}, expected 60"
    return "recalc.py computed the formula, 0 errors"


@check("pptx")
def check_pptx(tmp):
    """Generate a deck with pptxgenjs, then run the skill's OOXML validator on it."""
    script = tmp / "deck.js"
    script.write_text(
        "const pptxgen = require('pptxgenjs');\n"
        "const p = new pptxgen();\n"
        "p.layout = 'LAYOUT_16x9';\n"
        "const s = p.addSlide();\n"
        "s.addText('Toolchain check', {x:0.5, y:0.5, w:9, h:1, fontSize:36, color:'1E2761'});\n"
        "s.addNotes('generated by scripts/check-skills.py');\n"
        f"p.writeFile({{fileName: '{tmp / 'smoke.pptx'}'}});\n"
    )
    env = dict(os.environ, NODE_PATH=npm_root())
    run(["node", str(script)], cwd=tmp, env=env)

    deck = tmp / "smoke.pptx"
    assert deck.exists(), "pptxgenjs produced no file"

    validate = SKILLS / "pptx" / "scripts" / "office" / "validate.py"
    run([sys.executable, str(validate), str(deck)])
    return f"pptxgenjs wrote {deck.stat().st_size:,} bytes, validate.py passed"


@check("docx")
def check_docx(tmp):
    """Build a Word file with the docx npm library and read it back with pandoc."""
    script = tmp / "doc.js"
    script.write_text(
        "const {Document, Packer, Paragraph, HeadingLevel} = require('docx');\n"
        "const fs = require('fs');\n"
        "const doc = new Document({sections:[{children:[\n"
        "  new Paragraph({text:'Toolchain check', heading: HeadingLevel.HEADING_1}),\n"
        "  new Paragraph('The quick brown fox.'),\n"
        "]}]});\n"
        f"Packer.toBuffer(doc).then(b => fs.writeFileSync('{tmp / 'smoke.docx'}', b));\n"
    )
    env = dict(os.environ, NODE_PATH=npm_root())
    run(["node", str(script)], cwd=tmp, env=env)

    path = tmp / "smoke.docx"
    assert path.exists(), "docx-js produced no file"

    text = run(["pandoc", "-t", "markdown", str(path)]).stdout
    assert "quick brown fox" in text, f"pandoc did not read the body back:\n{text[:200]}"
    return "docx-js wrote the file, pandoc read it back"


@check("pdf")
def check_pdf(tmp):
    """Create a PDF with reportlab, then extract its text with both pdf readers."""
    from pdfplumber import open as pdfplumber_open
    from pypdf import PdfReader
    from reportlab.pdfgen import canvas

    path = tmp / "smoke.pdf"
    page = canvas.Canvas(str(path))
    page.drawString(72, 720, "Toolchain check")
    page.save()

    assert len(PdfReader(str(path)).pages) == 1, "pypdf saw the wrong page count"
    with pdfplumber_open(str(path)) as doc:
        text = doc.pages[0].extract_text() or ""
    assert "Toolchain check" in text, f"pdfplumber extracted {text!r}"
    return "reportlab wrote it, pypdf and pdfplumber read it"


@check("gif")
def check_gif(tmp):
    """Build a Slack-sized GIF through the skill's own GIFBuilder."""
    sys.path.insert(0, str(SKILLS / "slack-gif-creator"))
    from PIL import Image, ImageDraw

    from core.gif_builder import GIFBuilder

    builder = GIFBuilder(width=128, height=128, fps=10)
    for i in range(8):
        frame = Image.new("RGB", (128, 128), (240, 248, 255))
        draw = ImageDraw.Draw(frame)
        offset = i * 6
        draw.ellipse([20 + offset, 40, 60 + offset, 80], fill=(30, 95, 89))
        builder.add_frame(frame)

    path = tmp / "smoke.gif"
    builder.save(str(path), num_colors=48, optimize_for_emoji=True)
    size = path.stat().st_size
    assert size > 0, "GIFBuilder wrote an empty file"
    with Image.open(path) as img:
        assert img.size == (128, 128), f"got {img.size}, expected Slack emoji size"
    return f"GIFBuilder produced a 128x128 emoji GIF, {size:,} bytes"


@check("playwright")
def check_playwright(tmp):
    """Launch the image's chromium and render a page. Never runs `playwright install`."""
    from playwright.sync_api import sync_playwright

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page()
        page.set_content("<h1 id='t'>Toolchain check</h1>")
        text = page.inner_text("#t")
        page.screenshot(path=str(tmp / "smoke.png"))
        version = browser.version
        browser.close()

    assert text == "Toolchain check", f"page rendered {text!r}"
    assert (tmp / "smoke.png").stat().st_size > 0, "screenshot was empty"

    helper = SKILLS / "webapp-testing" / "scripts" / "with_server.py"
    run([sys.executable, str(helper), "--help"])
    return f"chromium {version} rendered and screenshotted, with_server.py runs"


@check("markitdown")
def check_markitdown(tmp):
    """The quick-look path the xlsx and pptx skills use for reading a file."""
    import openpyxl

    book = openpyxl.Workbook()
    book.active.title = "Numbers"
    book.active["A1"] = "widgets"
    path = tmp / "look.xlsx"
    book.save(path)

    out = run(["markitdown", str(path)]).stdout
    assert "widgets" in out, f"markitdown returned {out[:200]!r}"
    return "markitdown read a sheet back as text"


# --------------------------------------------------------------------------


def npm_root():
    return os.environ.get("NODE_PATH") or run(["npm", "root", "-g"]).stdout.strip()


def main():
    wanted = sys.argv[1:] or list(CHECKS)
    unknown = [n for n in wanted if n not in CHECKS]
    if unknown:
        print(f"unknown check(s): {', '.join(unknown)}", file=sys.stderr)
        print(f"available: {', '.join(CHECKS)}", file=sys.stderr)
        return 2

    if not SKILLS.is_dir():
        print(f"no skills found at {SKILLS}", file=sys.stderr)
        return 2

    failures = []
    print(f"Checking the skill toolchain {DIM}({len(wanted)} checks){OFF}\n")

    for name in wanted:
        tmp = Path(tempfile.mkdtemp(prefix=f"skillcheck-{name}-"))
        try:
            detail = CHECKS[name](tmp)
            print(f"  {GREEN}PASS{OFF}  {name:<11} {DIM}{detail}{OFF}")
        except Exception as exc:  # noqa: BLE001 - a check may fail any way it likes
            failures.append(name)
            print(f"  {RED}FAIL{OFF}  {name:<11} {exc}")
        finally:
            shutil.rmtree(tmp, ignore_errors=True)

    print()
    if failures:
        print(f"{RED}{len(failures)} of {len(wanted)} failed:{OFF} {', '.join(failures)}")
        print("Run .claude/hooks/session-start.sh to install what is missing.")
        return 1
    print(f"{GREEN}All {len(wanted)} checks passed.{OFF}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
